# Generated by Django 3.2.6 on 2021-08-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='p',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
